stages:
  - dependencies
  - build
  - host

install_dependencies:
  image: node:latest
  stage: dependencies
  script:
    - npm cache clean --force
    - npm install
  artifacts:
    paths:
      - node_modules

build_image:
  image: node:latest
  stage: build
  dependencies:
    - install_dependencies
  script:
    - npm link @angular/cli
    - ng build --verbose --progress --aot
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist

host_app:
  image: node:latest
  stage: host
  dependencies:
    - install_dependencies
  script:
    - npm install -g firebase-tools
    - firebase deploy --token "$FIREBASE_TOKEN"
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
