stages:
  - dependencies
  - test
  - build

install_dependencies:
  image: node:latest
  stage: dependencies
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

lint:
  image: node:latest
  stage: test
  dependencies:
    - install_dependencies
  script:
    - npm link @angular/cli
    - ng lint

build_image:
  image: node:latest
  stage: build
  dependencies:
    - install_dependencies
  script:
    - npm link @angular/cli
    - ng build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
